### ISSUE TITLE
No way to go back to users page when in thread list view for a specific user.

### ISSUE THREAD

**Issue by sangee2004** [otto8-ai/otto8#579] opened 2024-11-13 21:02 UTC
**Steps to reproduce the problem:**
1. Go to `Users` page and follow the link to open threads for any specific user.
2. Notice that we dont have a link to take up back to Users page. Have only option for Home which takes us to Agent list view.
<img width="1146" alt="Screenshot 2024-11-13 at 12 59 42 PM" src="https://github.com/user-attachments/assets/0ad700ab-c808-4dac-b35d-2dcdf09f9c67">

**Expected Behavior:**
Have a link to take users back to user list page.

Note - Using browser back button takes us to the user list as expected

**Comment by thedadams** [comment] 2024-11-14 12:44
Closing as a duplicate of the above issue. They are really the same thing.

**Closed by thedadams** 2024-11-14 12:44 UTC
Labels: bug, admin-ui
