### ISSUE TITLE
Should not be allowed to create multiple agents with same slug.

### ISSUE THREAD

**Issue by sangee2004** [otto8-ai/otto8#22] opened 2024-09-18 18:56 UTC
commit id - https://github.com/gptscript-ai/otto/commit/d7fcd7e9558315925edce265d96028bbdce6f9fd

**Steps to reproduce the problem:**

1. Create an agent with following file - otto create -f <file-name>
```
slug: "outlook"
name: "mail&calendar"
description: "Mail and calendar assistant"
tools: ["github.com/gptscript-ai/tools/apis/outlook/mail/manage","github.com/gptscript-ai/tools/apis/outlook/calendar/manage"]
prompt: "You are a good assistant.Wait for user to ask a question"
```
2. Create another agent with  the same file from step1 , but change the `name` to `mail&calendardupe`

Agent creation succeeds and we have 2 entries created. The invoke url for the 2nd entry does not have the `slug` value and instead has the id generated.

```
a1mllgr   mail&calendar         Mail and calendar assistant                                              http://localhost:8080/invoke/outlook
a1tg94b   mail&calendardupe     Mail and calendar assistant                                              http://localhost:8080/invoke/a1tg94b
```

When chatting with the agent using ` otto invoke outlook` , we see the first agent being used which is as expected. But misleading that the 2nd agent now has to use the id to be invoked.

**Expected Behavior:**
Should not be allowed to create multiple agents with same slug.

**Comment by thedadams** [comment] 2024-12-13 18:37
Slugs have been renamed to alias, but this is working as intended. Moving to "Testing" for verification.

**Comment by sangee2004** [comment] 2024-12-13 19:28
Tested with latest version.

1. Create an agent with alias - `outlooktest` using the following file 

```
alias: "outlooktest"
type: agent
name: "mail&calendartest"
description: "Mail and calendar assistant"
tools: ["github.com/otto8-ai/tools/outlook/mail","github.com/otto8-ai/tools/outlook/calendar"]
prompt: "You are a good assistant.Wait for user to ask a question"

```
Following agent gets created:
```
a1v5nq2   mail&calendartest   Mail and calendar assistant test   http://localhost:8080/api/invoke/outlooktest   4 seconds ago
```

2.  Create another agent with the same alias - `outlooktest` using the same file as above but just changing the name and desc to include "dupe" at the end.

Existing agent entry  gets updated with the latest updates:

```
a1v5nq2   mail&calendartestdupe   Mail and calendar assistant dupe   http://localhost:8080/api/invoke/outlooktest   33 seconds ago
````

**Closed** 2024-12-13 19:48 UTC
Labels: bug
